# Why do we use indicators?

In trading classification, traders often use indicators instead of just relying on the open, high, low, and close prices because 
- indicators can provide additional insights by mathematically calculating patterns and relationships within the price data, which can be harder to identify just by looking at raw price points alone.
- indicators help interpret the raw price information and provide a more nuanced view of the market.

## Import data (for testing)

In [1]:
import yfinance as yf
import pandas as pd
import numpy as np

In [2]:
pal = yf.download('CL=F', start = '2020-03-23', end = '2024-10-11')
#pal = yf.download('PA=F', start = '2020-03-23', end = '2024-10-11')
pal

[*********************100%***********************]  1 of 1 completed

                 Open       High        Low      Close  Adj Close  Volume
Date
2020-03-23  22.520000  24.070000  20.799999  23.360001  23.360001  852951
2020-03-24  23.870001  25.160000  23.090000  24.010000  24.010000  659697
2020-03-25  24.370001  25.240000  22.910000  24.490000  24.490000  618725
2020-03-26  24.250000  24.650000  22.379999  22.600000  22.600000  633877
2020-03-27  23.290001  23.440001  20.879999  21.510000  21.510000  603124
...               ...        ...        ...        ...        ...     ...
2024-10-04  73.949997  75.570000  73.459999  74.379997  74.379997  428815
2024-10-07  74.400002  77.400002  73.620003  77.139999  77.139999  419018
2024-10-08  77.330002  78.459999  72.690002  73.570000  73.570000  496760
2024-10-09  73.839996  74.449997  71.529999  73.239998  73.239998  401159
2024-10-10  73.389999  76.239998  73.260002  75.849998  75.849998  321453

[1147 rows x 6 columns]

## Technical indicators (from Predicting the direction of stock market prices using random forest)

### Relative Strength Index

- RSI determines whether the stock is overbought or oversold.
- Overbought:
  + demand unjustifiably pushes the price upwards
  + a sign that the stock is overvalued and the price is likely to go down.
- Oversold:
  + price goes down sharply to a level below its true value
  + result caused due to panic selling

$$ RSI = 100 - \frac{100}{1 + RS} $$

where

$$ RS = \frac{\text{Average Gain Over Past 14 days}}{\text{Average Loss Over past 14 days}} $$

- RSI ranges from 0 to 100.
  + RSI > 70: overbought
  + RSI < 30: oversold

In [5]:
# Calculate the 14 day RSI
n = 14

pal['change_in_price'] = pal['Close'].diff()

# First make a copy of the data frame twice
up_df, down_df = pal[['change_in_price']].copy(), pal[['change_in_price']].copy()

# For up days, if the change is less than 0 set to 0.
up_df.loc['change_in_price'] = up_df.loc[(up_df['change_in_price'] < 0), 'change_in_price'] = 0

# For down days, if the change is greater than 0 set to 0.
down_df.loc['change_in_price'] = down_df.loc[(down_df['change_in_price'] > 0), 'change_in_price'] = 0

# We need change in price to be absolute.
down_df['change_in_price'] = down_df['change_in_price'].abs()

# Calculate the EWMA (Exponential Weighted Moving Average), meaning older values are given less weight compared to newer values.
ewma_up = up_df['change_in_price'].transform(lambda x: x.ewm(span = n).mean())
ewma_down = down_df['change_in_price'].transform(lambda x: x.ewm(span = n).mean())

# Calculate the Relative Strength
relative_strength = ewma_up / ewma_down

# Calculate the Relative Strength Index
relative_strength_index = 100.0 - (100.0 / (1.0 + relative_strength))

# Add the info to the data frame.
pal['down_days'] = down_df['change_in_price']
pal['up_days'] = up_df['change_in_price']
#pal['RSI'] = relative_strength_index

relative_strength_index

Date
2020-03-23 00:00:00           NaN
2020-03-24 00:00:00    100.000000
2020-03-25 00:00:00    100.000000
2020-03-26 00:00:00     32.360417
2020-03-27 00:00:00     22.315915
                          ...
2024-10-07 00:00:00     78.248819
2024-10-08 00:00:00     57.066179
2024-10-09 00:00:00     55.464722
2024-10-10 00:00:00     64.544783
change_in_price         64.544783
Name: change_in_price, Length: 1148, dtype: float64

In [3]:
def RSI(df):
    
    df['change_in_price'] = df['Close'].diff()

    # First make a copy of the data frame twice
    up_df, down_df = df[['change_in_price']].copy(), df[['change_in_price']].copy()
    
    # For up days, if the change is less than 0 set to 0.
    up_df.loc['change_in_price'] = up_df.loc[(up_df['change_in_price'] < 0), 'change_in_price'] = 0
    
    # For down days, if the change is greater than 0 set to 0.
    down_df.loc['change_in_price'] = down_df.loc[(down_df['change_in_price'] > 0), 'change_in_price'] = 0
    
    # We need change in price to be absolute.
    down_df['change_in_price'] = down_df['change_in_price'].abs()
    
    # Calculate the EWMA (Exponential Weighted Moving Average), meaning older values are given less weight compared to newer values.
    ewma_up = up_df['change_in_price'].transform(lambda x: x.ewm(span = 14).mean())
    ewma_down = down_df['change_in_price'].transform(lambda x: x.ewm(span = 14).mean())
    
    # Calculate the Relative Strength
    relative_strength = ewma_up / ewma_down
    
    # Calculate the Relative Strength Index
    relative_strength_index = 100.0 - (100.0 / (1.0 + relative_strength))
    
    # Add the info to the data frame.
    df['RSI'] = relative_strength_index

    return df

In [4]:
RSI(pal)
pal

,Open,High,Low,Close,Adj Close,Volume,change_in_price,RSI
Date,,,,,,,,
2020-03-23,22.520000,24.070000,20.799999,23.360001,23.360001,852951,NaN,NaN
2020-03-24,23.870001,25.160000,23.090000,24.010000,24.010000,659697,0.650000,100.000000
2020-03-25,24.370001,25.240000,22.910000,24.490000,24.490000,618725,0.480000,100.000000
2020-03-26,24.250000,24.650000,22.379999,22.600000,22.600000,633877,-1.889999,32.360417
2020-03-27,23.290001,23.440001,20.879999,21.510000,21.510000,603124,-1.090000,22.315915
...,...,...,...,...,...,...,...,...
2024-10-04,73.949997,75.570000,73.459999,74.379997,74.379997,428815,0.669998,71.048192
2024-10-07,74.400002,77.400002,73.620003,77.139999,77.139999,419018,2.760002,78.248819
2024-10-08,77.330002,78.459999,72.690002,73.570000,73.570000,496760,-3.570000,57.066179
2024-10-09,73.839996,74.449997,71.529999,73.239998,73.239998,401159,-0.330002,55.464722
2024-10-10,73.389999,76.239998,73.260002,75.849998,75.849998,321453,2.610001,64.544783

### Stochastic Oscillator

- Measures the level of the closing price relative to low-high range over a period of time.
- Stochastic Oscillator follows the speed of the momentum of the price.
- Momentum changes before the price changes.

$$ \%K = 100 \cdot \frac{C - L14}{H14 - L14} $$

where
$$ C = \text{Current Closing Price} $$
$$ L14 = \text{Lowest Low over the past 14 days} $$
$$ H14 = \text{Highest High over the past 14 days} $$

In [9]:
# Calculate the Stochastic Oscillator
n = 14

# Make a copy of the high and low column.
low_14, high_14 = pal[['Low']].copy(), pal[['High']].copy()

# Apply the rolling function and grab the Min and Max.
low_14 = low_14['Low'].transform(lambda x: x.rolling(window = n).min())
high_14 = high_14['High'].transform(lambda x: x.rolling(window = n).max())

# Calculate the Stochastic Oscillator.
k_percent = 100 * ((pal['Close'] - low_14) / (high_14 - low_14))

# Add the info to the data frame.
pal['low_14'] = low_14
pal['high_14'] = high_14
#pal['k_percent'] = k_percent

k_percent

# pal

Date
2020-03-23          NaN
2020-03-24          NaN
2020-03-25          NaN
2020-03-26          NaN
2020-03-27          NaN
                ...
2024-10-04    87.121183
2024-10-07    97.651290
2024-10-08    59.686723
2024-10-09    56.966180
2024-10-10    78.483090
Length: 1147, dtype: float64

In [7]:
def SO(df):
    
    # Make a copy of the high and low column.
    low_14, high_14 = df[['Low']].copy(), df[['High']].copy()
    
    # Apply the rolling function and grab the Min and Max.
    low_14 = low_14['Low'].transform(lambda x: x.rolling(window = 14).min())
    high_14 = high_14['High'].transform(lambda x: x.rolling(window = 14).max())
    
    # Calculate the Stochastic Oscillator.
    k_percent = 100 * ((df['Close'] - low_14) / (high_14 - low_14))
    
    # Add the info to the data frame.
    #pal['low_14'] = low_14
    #pal['high_14'] = high_14
    df['k_percent'] = k_percent
    return df

In [8]:
SO(pal)
pal

,Open,High,Low,Close,Adj Close,Volume,change_in_price,RSI,down_days,up_days,low_14,high_14,k_percent
Date,,,,,,,,,,,,,
2020-03-23,22.520000,24.070000,20.799999,23.360001,23.360001,852951,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-24,23.870001,25.160000,23.090000,24.010000,24.010000,659697,0.650000,100.000000,0.000000,0.650000,NaN,NaN,NaN
2020-03-25,24.370001,25.240000,22.910000,24.490000,24.490000,618725,0.480000,100.000000,0.000000,0.480000,NaN,NaN,NaN
2020-03-26,24.250000,24.650000,22.379999,22.600000,22.600000,633877,-1.889999,32.360417,1.889999,0.000000,NaN,NaN,NaN
2020-03-27,23.290001,23.440001,20.879999,21.510000,21.510000,603124,-1.090000,22.315915,1.090000,0.000000,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-04,73.949997,75.570000,73.459999,74.379997,74.379997,428815,0.669998,71.048192,0.000000,0.669998,66.330002,75.570000,87.121183
2024-10-07,74.400002,77.400002,73.620003,77.139999,77.139999,419018,2.760002,78.248819,0.000000,2.760002,66.330002,77.400002,97.651290
2024-10-08,77.330002,78.459999,72.690002,73.570000,73.570000,496760,-3.570000,57.066179,3.570000,0.000000,66.330002,78.459999,59.686723
2024-10-09,73.839996,74.449997,71.529999,73.239998,73.239998,401159,-0.330002,55.464722,0.330002,0.000000,66.330002,78.459999,56.966180
2024-10-10,73.389999,76.239998,73.260002,75.849998,75.849998,321453,2.610001,64.544783,0.000000,2.610001,66.330002,78.459999,78.483090

### William %R

- Indicates sell signal and buy signal

$$ \%R = -100 \cdot \frac{H14 - C}{H14 - L14} $$

where
$$ C = \text{Current Closing Price} $$
$$ L14 = \text{Lowest Low over the past 14 days} $$
$$ H14 = \text{Highest High over the past 14 days} $$

- %R ranges from -100 to 0.
  + %R > -20: sell signal
  + %R < -80: buy signal

In [11]:
# Calculate the Williams %R
n = 14

# Make a copy of the high and low column.
low_14, high_14 = pal[['Low']].copy(), pal[['High']].copy()

# Group by symbol, then apply the rolling function and grab the Min and Max.
low_14 = low_14['Low'].transform(lambda x: x.rolling(window = n).min())
high_14 = high_14['High'].transform(lambda x: x.rolling(window = n).max())

# Calculate William %R indicator.
r_percent = -100 * ((high_14 - pal['Close']) / (high_14 - low_14))

r_percent
# Add the info to the data frame.
#pal['r_percent'] = r_percent
#pal

Date
2020-03-23          NaN
2020-03-24          NaN
2020-03-25          NaN
2020-03-26          NaN
2020-03-27          NaN
                ...
2024-10-04   -12.878817
2024-10-07    -2.348710
2024-10-08   -40.313277
2024-10-09   -43.033820
2024-10-10   -21.516910
Length: 1147, dtype: float64

In [12]:
def r_percent(df):
    
    # Make a copy of the high and low column.
    low_14, high_14 = df[['Low']].copy(), df[['High']].copy()
    
    # Group by symbol, then apply the rolling function and grab the Min and Max.
    low_14 = low_14['Low'].transform(lambda x: x.rolling(window = 14).min())
    high_14 = high_14['High'].transform(lambda x: x.rolling(window = 14).max())
    
    # Calculate William %R indicator.
    r_percent = -100 * ((high_14 - pal['Close']) / (high_14 - low_14))
    
    df['r_percent'] = r_percent

    return df

In [13]:
r_percent(pal)

,Open,High,Low,Close,Adj Close,Volume,change_in_price,RSI,down_days,up_days,low_14,high_14,k_percent,r_percent
Date,,,,,,,,,,,,,,
2020-03-23,22.520000,24.070000,20.799999,23.360001,23.360001,852951,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-24,23.870001,25.160000,23.090000,24.010000,24.010000,659697,0.650000,100.000000,0.000000,0.650000,NaN,NaN,NaN,NaN
2020-03-25,24.370001,25.240000,22.910000,24.490000,24.490000,618725,0.480000,100.000000,0.000000,0.480000,NaN,NaN,NaN,NaN
2020-03-26,24.250000,24.650000,22.379999,22.600000,22.600000,633877,-1.889999,32.360417,1.889999,0.000000,NaN,NaN,NaN,NaN
2020-03-27,23.290001,23.440001,20.879999,21.510000,21.510000,603124,-1.090000,22.315915,1.090000,0.000000,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-04,73.949997,75.570000,73.459999,74.379997,74.379997,428815,0.669998,71.048192,0.000000,0.669998,66.330002,75.570000,87.121183,-12.878817
2024-10-07,74.400002,77.400002,73.620003,77.139999,77.139999,419018,2.760002,78.248819,0.000000,2.760002,66.330002,77.400002,97.651290,-2.348710
2024-10-08,77.330002,78.459999,72.690002,73.570000,73.570000,496760,-3.570000,57.066179,3.570000,0.000000,66.330002,78.459999,59.686723,-40.313277
2024-10-09,73.839996,74.449997,71.529999,73.239998,73.239998,401159,-0.330002,55.464722,0.330002,0.000000,66.330002,78.459999,56.966180,-43.033820
2024-10-10,73.389999,76.239998,73.260002,75.849998,75.849998,321453,2.610001,64.544783,0.000000,2.610001,66.330002,78.459999,78.483090,-21.516910

### Moving Average Convergence Divergence (MACD)

- Also indicates sell signal and buy signal.

$$ \text{MACD} = \text{EMA}_{12}(C) - \text{EMA}_{26}(C) $$ 

and 

$$ \text{Signal Line} = \text{EMA}_9 (\text{MACD}) $$
 
where 
$$ \text{MACD} = \text{Moving Average Convergence Divergence} $$
$$ C = \text{Closing Price series} $$
$$ \text{EMA}_n = n \hspace{1mm} \text{day Exponential Moving Average} $$
- EMA stands for Exponential Moving Average.
- MACD < Signal Line: sell signal
- MACD > Signal Line: buy signal

In [14]:
# Calculate the MACD
ema_26 = pal['Close'].transform(lambda x: x.ewm(span = 26).mean())
ema_12 = pal['Close'].transform(lambda x: x.ewm(span = 12).mean())
macd = ema_12 - ema_26

# Calculate the EMA
ema_9_macd = macd.ewm(span = 9).mean()

# Store the data in the data frame.
#pal['MACD'] = macd
#pal['MACD_EMA'] = ema_9_macd # signal line

# Print the head.
#pal

In [ ]:
def MACD(df):
    ema_26 = df['Close'].transform(lambda x: x.ewm(span = 26).mean())
    ema_12 = df ['Close'].transform(lambda x: x.ewm(span = 12).mean())
    macd = ema_12 - ema_26
    
    # Calculate the EMA
    ema_9_macd = macd.ewm(span = 9).mean()
    
    # Store the data in the data frame.
    df['MACD'] = macd
    df['MACD_EMA'] = ema_9_macd # signal line

    return df

### Price Rate of Change

- Measures the most recent change in price with respect to the price in n days ago.

$$ \text{PROC} = \frac{C(t) - C(t - n)}{C(t - n)} $$

where 
$$ \text{PROC}(t) = \text{Price Rate of Change at time} \hspace{1mm} t $$
$$ C(t) = \text{Closing Price at time} \hspace{1mm} t $$

In [7]:
# Calculate the Price Rate of Change
n = 9

# Calculate the Rate of Change in the Price, and store it in the Data Frame.
pal['Price_Rate_Of_Change'] = pal['Close'].transform(lambda x: x.pct_change(periods = n))

# Print the first 30 rows
#pal

,Open,High,Low,Close,Adj Close,Volume,change_in_price,down_days,up_days,RSI,low_14,high_14,k_percent,r_percent,MACD,MACD_EMA,Price_Rate_Of_Change
Date,,,,,,,,,,,,,,,,,
2020-03-23,22.520000,24.070000,20.799999,23.360001,23.360001,852951,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN
2020-03-24,23.870001,25.160000,23.090000,24.010000,24.010000,659697,0.650000,0.000000,0.650000,100.000000,NaN,NaN,NaN,NaN,0.014583,0.008102,NaN
2020-03-25,24.370001,25.240000,22.910000,24.490000,24.490000,618725,0.480000,0.000000,0.480000,100.000000,NaN,NaN,NaN,NaN,0.033467,0.018497,NaN
2020-03-26,24.250000,24.650000,22.379999,22.600000,22.600000,633877,-1.889999,1.889999,0.000000,32.360417,NaN,NaN,NaN,NaN,-0.027003,0.003084,NaN
2020-03-27,23.290001,23.440001,20.879999,21.510000,21.510000,603124,-1.090000,1.090000,0.000000,22.315915,NaN,NaN,NaN,NaN,-0.102666,-0.028374,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-04,73.949997,75.570000,73.459999,74.379997,74.379997,428815,0.669998,0.000000,0.669998,71.048192,66.330002,75.570000,87.121183,-12.878817,-0.271527,-0.951417,0.056984
2024-10-07,74.400002,77.400002,73.620003,77.139999,77.139999,419018,2.760002,0.000000,2.760002,78.248819,66.330002,77.400002,97.651290,-2.348710,0.243016,-0.712530,0.077977
2024-10-08,77.330002,78.459999,72.690002,73.570000,73.570000,496760,-3.570000,3.570000,0.000000,57.066179,66.330002,78.459999,59.686723,-40.313277,0.358591,-0.498306,0.055675
2024-10-09,73.839996,74.449997,71.529999,73.239998,73.239998,401159,-0.330002,0.330002,0.000000,55.464722,66.330002,78.459999,56.966180,-43.033820,0.418731,-0.314899,0.082311
2024-10-10,73.389999,76.239998,73.260002,75.849998,75.849998,321453,2.610001,0.000000,2.610001,64.544783,66.330002,78.459999,78.483090,-21.516910,0.669282,-0.118063,0.112496

In [15]:
def PROC(df, n):
    
    df['Price_Rate_Of_Change'] = df['Close'].transform(lambda x: x.pct_change(periods = n))
    return df

### On Balance Volume

- Finds buying and selling trends of a stock

$$ \text{OBV}(t) = \left\{
\begin{array}{ll}
      \text{OBV}(t - 1) + \text{Vol}(t) & \text{if} \hspace{1mm} C(t) > C(t - 1) \\
      \text{OBV}(t - 1) - \text{Vol}(t) & \text{if} \hspace{1mm} C(t) < C(t - 1) \\
      \text{OBV}(t - 1) & \text{if} \hspace{1mm} C(t) = C(t - 1) \\
\end{array} 
\right. $$

where

$$ \text{OBV}(t) = \text{On Balance Volume at time} \hspace{1mm} t $$
$$ \text{Vol}(t) = \text{Trading Volume at time} \hspace{1mm} t $$
$$ C(t) = \text{Closing Price at time} \hspace{1mm} t $$

In [22]:
# Grab the volume and close columns
volume = pal['Volume'].copy()
change = pal['Close'].copy()

#print(volume)

# Initialize the previous OBV
prev_obv = 0
obv_values = []

for i, j in zip(change, volume):
    if i > 0:
        current_obv = prev_obv + j
    elif i < 0:
        current_obv = prev_obv - j
    else:
        current_obv = prev_obv

    prev_obv = current_obv
    obv_values.append(current_obv)

print(pd.Series(obv_values))

pal['On Balance Volume'] = pd.Series(obv_values, index = pal.index)
pal

0          852951
1         1512648
2         2131373
3         2765250
4         3368374
          ...
1142    401714043
1143    402133061
1144    402629821
1145    403030980
1146    403352433
Length: 1147, dtype: int64

,Open,High,Low,Close,Adj Close,Volume,change_in_price,down_days,up_days,RSI,low_14,high_14,k_percent,r_percent,MACD,MACD_EMA,Price_Rate_Of_Change,On Balance Volume
Date,,,,,,,,,,,,,,,,,,
2020-03-23,22.520000,24.070000,20.799999,23.360001,23.360001,852951,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,852951
2020-03-24,23.870001,25.160000,23.090000,24.010000,24.010000,659697,0.650000,0.000000,0.650000,100.000000,NaN,NaN,NaN,NaN,0.014583,0.008102,NaN,1512648
2020-03-25,24.370001,25.240000,22.910000,24.490000,24.490000,618725,0.480000,0.000000,0.480000,100.000000,NaN,NaN,NaN,NaN,0.033467,0.018497,NaN,2131373
2020-03-26,24.250000,24.650000,22.379999,22.600000,22.600000,633877,-1.889999,1.889999,0.000000,32.360417,NaN,NaN,NaN,NaN,-0.027003,0.003084,NaN,2765250
2020-03-27,23.290001,23.440001,20.879999,21.510000,21.510000,603124,-1.090000,1.090000,0.000000,22.315915,NaN,NaN,NaN,NaN,-0.102666,-0.028374,NaN,3368374
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-04,73.949997,75.570000,73.459999,74.379997,74.379997,428815,0.669998,0.000000,0.669998,71.048192,66.330002,75.570000,87.121183,-12.878817,-0.271527,-0.951417,0.056984,401714043
2024-10-07,74.400002,77.400002,73.620003,77.139999,77.139999,419018,2.760002,0.000000,2.760002,78.248819,66.330002,77.400002,97.651290,-2.348710,0.243016,-0.712530,0.077977,402133061
2024-10-08,77.330002,78.459999,72.690002,73.570000,73.570000,496760,-3.570000,3.570000,0.000000,57.066179,66.330002,78.459999,59.686723,-40.313277,0.358591,-0.498306,0.055675,402629821
2024-10-09,73.839996,74.449997,71.529999,73.239998,73.239998,401159,-0.330002,0.330002,0.000000,55.464722,66.330002,78.459999,56.966180,-43.033820,0.418731,-0.314899,0.082311,403030980
2024-10-10,73.389999,76.239998,73.260002,75.849998,75.849998,321453,2.610001,0.000000,2.610001,64.544783,66.330002,78.459999,78.483090,-21.516910,0.669282,-0.118063,0.112496,403352433

In [ ]:
sns.countplot(data=data, y='category_column', order=category_counts.index)
   plt.show()

## Bollinger upper and lower

In [ ]:
def Bollinger_Bands(df, window=20):
    # Calculate the 20-day simple moving average (SMA)
    sma = df['Close'].rolling(window=window).mean()
    
    # Calculate the rolling standard deviation
    rolling_std = df['Close'].rolling(window=window).std()
    
    # Calculate the upper and lower Bollinger Bands
    df['Bollinger_Upper'] = sma + (rolling_std * 2)  # Upper band
    df['Bollinger_Lower'] = sma - (rolling_std * 2)  # Lower band
    
    return df